# Generated by Django 4.0 on 2021-12-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='rummyResultClose',
            new_name='resultClose',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='rummyResultOpen',
            new_name='resultOpen',
        ),
        migrations.RemoveField(
            model_name='market',
            name='jokerResultClose',
        ),
        migrations.RemoveField(
            model_name='market',
            name='jokerResultOpen',
        ),
        migrations.AddField(
            model_name='biddinghistory',
            name='cardPattern',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='market',
            name='closeResultPattern',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='market',
            name='openResultPattern',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='market',
            name='remark',
            field=models.CharField(default='', max_length=300),
        ),
    ]
