# Generated by Django 4.0 on 2021-12-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_rummyresultclose_market_resultclose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelchartjodimarket',
            name='resultDigit',
            field=models.TextField(default='**'),
        ),
        migrations.AlterField(
            model_name='panelchartregulermarket',
            name='CloseSingleDigit',
            field=models.TextField(default='***'),
        ),
        migrations.AlterField(
            model_name='panelchartregulermarket',
            name='closeThreeDigit',
            field=models.TextField(default='***'),
        ),
        migrations.AlterField(
            model_name='panelchartregulermarket',
            name='openSingleDigit',
            field=models.TextField(default='***'),
        ),
        migrations.AlterField(
            model_name='panelchartregulermarket',
            name='openThreeDigit',
            field=models.TextField(default='***'),
        ),
    ]
