# Generated by Django 4.0 on 2021-12-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_panelchartjodimarket_resultdigit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jodibiddinghistory',
            name='digit',
        ),
        migrations.AddField(
            model_name='jodibiddinghistory',
            name='cardPattern',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='jodibiddinghistory',
            name='resultCard',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jodimarket',
            name='resultPattern',
            field=models.TextField(default='**'),
        ),
        migrations.AlterField(
            model_name='jodimarket',
            name='result',
            field=models.TextField(default='**'),
        ),
    ]
