# Generated by Django 4.0 on 2021-12-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_jodibiddinghistory_digit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jodibiddinghistory',
            name='resultCard',
            field=models.TextField(default='**'),
        ),
    ]
