# Generated by Django 4.0.4 on 2022-06-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_jodibiddinghistory_resultcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=200)),
                ('unit', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='', upload_to='dashboard/images/card')),
            ],
        ),
    ]
